# Generated by Django 2.0.5 on 2018-05-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='attempted',
        ),
    ]
