# Generated by Django 2.0.5 on 2018-05-12 08:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oj_name', models.CharField(max_length=20)),
                ('oj_username', models.CharField(max_length=30)),
                ('oj_password', models.CharField(max_length=100)),
                ('oj_account_status', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('cookies', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'remote_account',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oj_name', models.CharField(max_length=20)),
                ('oj_language', models.CharField(max_length=40)),
                ('oj_language_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'remote_language',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('oj_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('oj_value', models.TextField()),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'setting',
            },
        ),
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('oj_name', 'oj_language')},
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('oj_name', 'oj_username')},
        ),
    ]
