# Generated by Django 2.0.5 on 2018-05-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('oj_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('oj_proxy', models.CharField(max_length=200)),
                ('oj_proxy_type', models.CharField(default='socks', max_length=10)),
            ],
            options={
                'db_table': 'remote_proxy',
            },
        ),
    ]
