# Generated by Django 2.1.2 on 2018-12-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
