# Generated by Django 2.0.5 on 2018-05-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='hook',
            field=models.BooleanField(default=False),
        ),
    ]
