# Generated by Django 2.0.5 on 2018-05-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_submission_hook'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='sha256',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
