# Generated by Django 2.1.2 on 2018-12-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20181225_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict_code',
            field=models.CharField(default='In Queue', max_length=50),
        ),
    ]
