# Generated by Django 2.0.5 on 2018-05-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_submission_sha256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='contest_id',
        ),
    ]
