# Generated by Django 2.1.2 on 2018-12-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_auto_20181225_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='remote_run_id',
            new_name='unique_key',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='verdict_code',
        ),
        migrations.AddField(
            model_name='submission',
            name='verdict_info',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='compile_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
