# Generated by Django 2.1.2 on 2018-12-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20181228_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reloadable',
            field=models.BooleanField(default=False),
        ),
    ]
