# Generated by Django 2.0.5 on 2018-05-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20180528_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(default='Waiting', max_length=40, null=True),
        ),
    ]
