# Generated by Django 2.1.2 on 2018-12-05 02:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oj_name', models.CharField(max_length=20)),
                ('oj_username', models.CharField(max_length=30)),
                ('oj_password', models.CharField(max_length=100)),
                ('oj_account_status', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('cookies', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oj_name', models.CharField(max_length=20)),
                ('oj_language', models.CharField(max_length=40)),
                ('oj_language_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('oj_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('oj_value', models.TextField()),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'setting',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('oj_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('oj_proxies', models.CharField(default=None, max_length=200)),
                ('oj_enable', models.BooleanField(default=False)),
                ('oj_status', models.CharField(choices=[('PENDING', '等待中'), ('SUCCEED', '成功'), ('FAILED', '失败')], default='PENDING', max_length=20)),
            ],
            options={
                'db_table': 'support',
            },
        ),
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('oj_name', 'oj_language')},
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('oj_name', 'oj_username')},
        ),
    ]
