# Generated by Django 2.1.2 on 2018-12-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20181205_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='oj_account_status',
        ),
        migrations.AlterField(
            model_name='support',
            name='oj_status',
            field=models.CharField(choices=[('PENDING', '等待中'), ('SUCCESS', '成功'), ('FAILED', '失败')], default='PENDING', max_length=20),
        ),
    ]
