# Generated by Django 2.1.2 on 2018-12-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_auto_20181226_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
