# Generated by Django 2.1.2 on 2018-12-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='oj_reuse',
            field=models.BooleanField(default=True),
        ),
    ]
