# Generated by Django 3.0.3 on 2020-02-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('enable', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'platform',
            },
        ),
    ]
