# Generated by Django 3.0.3 on 2020-02-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_language'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('platform', 'key')},
        ),
    ]
