# Generated by Django 2.1.2 on 2018-12-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_oj', models.CharField(max_length=20)),
                ('remote_id', models.CharField(max_length=20)),
                ('remote_url', models.CharField(max_length=200, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('request_status', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200, null=True)),
                ('time_limit', models.CharField(max_length=20, null=True)),
                ('memory_limit', models.CharField(max_length=20, null=True)),
                ('special_judge', models.BooleanField(default=False)),
                ('html', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'problem',
                'ordering': ('update_time',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('remote_oj', 'remote_id')},
        ),
    ]
