# Generated by Django 2.0.5 on 2018-05-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
