# Generated by Django 3.0.3 on 2020-02-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20181225_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.IntegerField()),
                ('index', models.CharField(max_length=20)),
                ('user', models.IntegerField()),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'request',
            },
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='remote_id',
            new_name='index',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='special_judge',
            new_name='spj',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='remote_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='problem',
            name='platform',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('platform', 'index')},
        ),
        migrations.RemoveField(
            model_name='problem',
            name='remote_oj',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='request_status',
        ),
    ]
