# Generated by Django 3.0.3 on 2020-02-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20200208_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='platform',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
