# Generated by Django 3.0.3 on 2020-02-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20200208_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='platform',
            field=models.CharField(max_length=20),
        ),
    ]
