# Generated by Django 3.0.3 on 2020-02-10 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0003_auto_20200210_2001'),
        ('problem', '0006_auto_20200210_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='destination.Platform'),
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('platform', 'index')},
        ),
    ]
