# Generated by Django 2.1.2 on 2018-12-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hook_times',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
